language: php
services:
  - mysql
php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  
before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql -e "create database test;"
  - sudo mysql -e "use test;CREATE TABLE `l_user` ( `id` int(11) NOT NULL AUTO_INCREMENT, `code` char(12) DEFAULT NULL, `name` varchar(32) DEFAULT NULL, `add_time` int(11) DEFAULT NULL, `email_id` int(11) DEFAULT NULL,  PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8"
  - sudo mysql -e "use test;CREATE TABLE `l_user_nx` (  `id` int(11) NOT NULL AUTO_INCREMENT,`is_del` int(1) NOT NULL, `user_id` int(11) NOT NULL,  `email_id` char(12) DEFAULT NULL,  PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;"
  - sudo mysql -e "use test;CREATE TABLE `l_email` (`id` int(11) NOT NULL AUTO_INCREMENT,`user_id` char(12) DEFAULT NULL,`mail` char(12) DEFAULT NULL,PRIMARY KEY (`id`)) ENGINE=InnoDB AUTO_INCREMENT=347 DEFAULT CHARSET=utf8"
  - sudo service mysql restart
  
before_script:
  - composer install --dev
  - cd tests
script: 
  - ../vendor/bin/phpunit -v
after_script:
  - cd ..
  - travis_retry vendor/bin/php-coveralls -x tests/report/clover.xml -o tests/report/coveralls.json -v
